In [25]:
!mkdir RegressionFolder data

mkdir: RegressionFolder: File exists
mkdir: data: File exists

In [26]:
import pandas as pd

In [27]:
df = pd.read_csv ('RegressionFolder/Landuse.csv')

In [28]:
df

,Time,Unnamed: 1,Unnamed: 2,Unnamed: 3,1990,1991,1992,1993,1994,1995,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Country,NaN,Unit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Australia,NaN,"Hectares, Thousands",i,"464,026.5","462,763.4","465,953.5","460,097.3","469,047.6","463,347.3",...,"397,451.0","391,686.2","405,473.6","396,615.3","406,269.0","384,557.9","371,078.3","393,797.2",..,..
2,Austria,NaN,"Hectares, Thousands",i,"3,458.0","3,477.0","3,467.8","3,448.3","3,449.3",..,...,"3,166.0","2,868.0","2,864.0","2,862.0","2,716.0","2,720.0","2,689.0","2,656.0","2,654.0","2,652.0"
3,Belgium,NaN,"Hectares, Thousands",i,"1,384.0","1,374.8","1,353.8","1,370.8","1,370.2","1,385.8",...,"1,358.0","1,337.0","1,334.0","1,339.0","1,333.0","1,331.0","1,353.0","1,329.0","1,356.0","1,359.0"
4,Canada,NaN,"Hectares, Thousands",i,"58,580.7","60,891.4","60,207.3","60,761.7","61,398.5","60,801.5",...,"64,627.4","65,066.5","68,418.4","68,036.6","67,516.7","67,552.3","68,141.0","69,855.0","68,117.0",..
5,Chile,NaN,"Hectares, Thousands",i,"15,899.0","15,789.0","15,556.0","15,477.0","15,450.0","15,330.0",...,"15,743.0","15,789.0","15,755.0","15,781.0","15,761.2","15,785.0","15,741.8","15,747.0",..,..
6,Colombia,NaN,"Hectares, Thousands",i,"45,083.0","44,884.0","44,983.0","44,903.0","44,865.0","44,513.0",...,"42,503.0","41,721.0","42,617.6","44,815.6","44,784.7","44,753.9","44,723.0","49,499.0","49,492.0",..
7,Costa Rica,NaN,"Hectares, Thousands",i,"2,198.6","2,203.6","2,160.0","2,113.0","2,095.0","2,048.0",...,"1,819.0","1,819.0","1,812.0","1,801.0","1,778.0","1,777.5","1,777.5","1,779.5","1,782.5",..
8,Czech Republic,NaN,"Hectares, Thousands",i,"4,288.0","4,285.0","4,283.0","4,282.0","4,281.0","4,280.0",...,"3,524.0","3,504.0","3,526.0","3,521.0","3,516.0","3,494.0","3,489.0","3,521.0","3,523.0","3,524.0"
9,Denmark,NaN,"Hectares, Thousands",i,"2,788.3","2,785.7","2,755.3","2,710.9","2,712.6","2,721.6",...,"2,676.0","2,673.0","2,664.0","2,628.0","2,652.0","2,633.0","2,625.0","2,631.0","2,633.0","2,626.0"
10,Estonia,NaN,"Hectares, Thousands",i,"1,357.8","1,374.5","1,374.1","1,320.6","1,100.7",990.8,...,949.0,946.0,956.0,966.0,975.0,994.0,"1,004.0",982.0,985.0,988.0
11,Finland,NaN,"Hectares, Thousands",i,"2,559.7","2,539.2","2,528.5","2,292.9","2,318.0","2,161.1",...,"2,292.0","2,287.0","2,285.0","2,259.0","2,267.0","2,273.0","2,275.0","2,272.0","2,272.0","2,274.0"
12,France,NaN,"Hectares, Thousands",i,"30,494.2","30,369.3","30,230.9","30,121.3","30,037.5","30,017.4",...,"29,311.0","28,853.0","29,001.0","28,976.0","28,930.0","29,115.0","29,089.0","29,101.0","29,020.0","29,024.0"
13,Germany,NaN,"Hectares, Thousands",i,"17,869.1","17,136.5","16,950.1","17,219.5","17,354.3","17,344.3",...,"16,704.0","16,721.0","16,667.0","16,700.0","16,725.0","16,731.0","16,659.0","16,687.0","16,645.0","16,666.0"
14,Greece,NaN,"Hectares, Thousands",i,"5,180.1","5,169.4","5,180.7","5,161.9","5,115.9","5,116.0",...,"5,426.0","5,532.0","5,135.0","5,213.0","5,407.0","5,292.0","5,260.0","5,152.0","5,288.0","5,153.0"
15,Hungary,NaN,"Hectares, Thousands",i,"6,473.1","6,459.7","6,135.7","6,129.1","6,122.0","6,179.3",...,"5,343.0","5,337.0","5,338.0","5,340.0","5,346.0","5,346.0","5,349.0","5,352.0","5,344.0","5,310.0"
16,Iceland,NaN,"Hectares, Thousands",i,"1,907.3","1,906.9","1,906.4","1,906.1","1,906.9","1,907.2",...,"1,591.0","1,591.0","1,591.0","1,591.0","1,591.0","1,591.0","1,591.0","1,591.0","1,591.0",..
17,Ireland,NaN,"Hectares, Thousands",i,"4,536.4","4,443.8","4,415.2","4,406.3","4,392.7","4,388.5",...,"4,569.0","4,556.0","4,532.0","4,478.0","4,465.0","4,431.0","4,461.0","4,489.0","4,516.0","4,524.0"
18,Israel,NaN,"Hectares, Thousands",i,435.0,435.0,435.0,435.0,435.0,430.0,...,283.2,289.2,298.3,292.3,309.8,306.0,308.2,297.1,293.5,..
19,Italy,NaN,"Hectares, Thousands",i,"18,166.3","17,570.6","17,203.0","16,484.1","16,426.0","16,172.3",...,"12,885.0","12,670.0","12,548.0","12,426.0","12,720.0","12,661.0","12,843.0","13,006.0","12,909.0","13,150.0"
20,Japan,NaN,"Hectares, Thousands",i,"5,242.7","5,204.7","5,164.5","5,124.8","5,082.0","5,038.3",...,"4,592.3","4,560.9","4,549.5","4,536.6","4,518.4","4,495.9","4,471.5","4,443.7","4,419.2",..
21,Korea,NaN,"Hectares, Thousands",i,"2,199.0","2,181.0","2,158.0","2,131.0","2,099.0","2,051.0",...,"1,754.0","1,737.0","1,768.0","1,749.0","1,727.1","1,714.0","1,678.1","1,654.8",..,..
22,Latvia,NaN,"Hectares, Thousands",i,"2,539.6","2,523.3","2,466.3","2,292.2","2,052.4","2,540.3",...,"1,806.0","1,816.0","1,841.0","1,878.0","1,873.0","1,885.0","1,931.0","1,932.0","1,938.0","1,959.0"
23,Lithuania,NaN,"Hectares, Thousands",i,"3,513.5","3,511.6","3,524.1","3,519.3","3,513.0","3,506.8",...,"2,772.0","2,806.0","2,842.0","2,891.0","2,952.0","3,006.0","2,954.0","2,935.0","2,947.0","2,975.0"
24,Luxembourg,NaN,"Hectares, Thousands",i,126.6,125.6,125.7,127.3,126.8,127.0,...,131.0,131.0,131.0,131.0,131.0,131.0,131.0,131.0,132.0,132.0
25,Mexico,NaN,"Hectares, Thousands",i,"105,151.0","106,154.0","106,177.0","106,180.0","106,190.0","106,195.0",...,"102,844.0","103,073.0","102,138.0","101,586.0","101,407.0","103,212.0","104,992.0","106,964.0",..,..
26,Netherlands,NaN,"Hectares, Thousands",i,"2,019.3","1,970.5","1,964.5","1,966.8","1,960.5","1,963.5",...,"1,872.0","1,858.0","1,842.0","1,848.0","1,839.0","1,846.0","1,796.0","1,790.0","1,822.0","1,816.0"
27,New Zealand,NaN,"Hectares, Thousands",i,"13,163.8","13,150.7","13,137.2","13,092.2","13,036.4","12,952.2",...,"11,408.0","11,371.0","11,209.0","11,106.0","11,122.0","10,850.0","10,674.0","10,779.0","10,632.0",..
28,Norway,NaN,"Hectares, Thousands",i,..,..,..,..,..,"1,025.5",...,"1,006.0",999.0,993.0,987.0,987.0,986.0,983.0,..,986.0,..
29,Poland,NaN,"Hectares, Thousands",i,"18,645.6","18,600.5","18,535.1","18,476.6","18,449.9","18,411.9",...,"14,603.0","14,780.0","14,529.0","14,410.0","14,424.0","14,398.0","14,406.0","14,498.0","14,540.0",..
30,Portugal,NaN,"Hectares, Thousands",i,"4,019.0","4,120.9","4,052.9","4,033.0","4,046.6","4,001.9",...,"3,654.0","3,650.0","3,665.0","3,718.0","3,700.0","3,695.0","3,636.0","3,603.0","3,591.0",..
31,Slovak Republic,NaN,"Hectares, Thousands",i,"2,416.6","2,416.6","2,418.8","2,420.7","2,446.0","2,445.9",...,"1,922.0","1,930.0","1,927.0","1,929.0","1,925.0","1,922.0","1,919.0","1,911.0","1,920.0","1,916.0"
32,Slovenia,NaN,"Hectares, Thousands",i,..,841.9,567.2,565.4,522.0,538.0,...,483.0,458.0,480.0,479.0,482.0,477.0,478.0,481.0,478.0,480.0
33,Spain,NaN,"Hectares, Thousands",i,"30,625.2","30,054.1","30,000.0","29,755.9","29,597.5","29,863.7",...,"23,719.0","23,894.0","23,463.0","23,495.0","23,572.0","23,897.0","23,816.0","23,841.0","24,202.0","24,372.0"
34,Sweden,NaN,"Hectares, Thousands",i,"3,416.4","3,358.0","3,336.0","3,200.8","3,371.0","3,148.2",...,"3,074.0","3,063.0","3,032.0","3,036.0","3,036.0","3,028.0","3,021.0","3,011.0","3,000.0","3,005.0"
35,Switzerland,NaN,"Hectares, Thousands",i,..,..,..,..,..,..,...,"1,537.0","1,534.0","1,531.0","1,529.0","1,526.0","1,523.0","1,521.0","1,518.0","1,515.0","1,512.0"
36,Turkey,NaN,"Hectares, Thousands",i,"42,003.0","40,031.0","39,952.0","39,912.0","40,048.0","39,211.0",...,"39,011.7","38,230.7","38,398.7","38,421.7","38,559.7","38,550.7","38,327.7","37,963.0","37,797.0",..
37,United Kingdom,NaN,"Hectares, Thousands",i,"16,998.5","16,928.3","16,851.7","16,355.5","16,177.0","16,126.0",...,"17,231.0","17,172.0","17,282.0","17,259.0","17,240.0","17,144.0","17,357.0","17,472.0","17,357.0","17,529.0"
38,United States,NaN,"Hectares, Thousands",i,"426,948.0","426,948.0","425,429.0","422,948.0","421,139.0","420,139.0",...,"408,426.2","406,927.7","423,893.2","422,481.0","424,330.2","422,568.3","422,826.2","422,826.2",..,..
39,European Union (28 countries),NaN,"Hectares, Thousands",i,..,..,..,..,..,..,...,"180,137.0","179,365.0","178,198.0","178,099.0","178,393.0","178,996.0","178,751.0","178,822.0","179,145.0",..
40,Non-OECD Economies,NaN,NaN,NaN,..,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
41,Non-OECD Economies,Argentina,"Hectares, Thousands",i,"127,565.0","127,660.0","127,755.0","127,850.0","127,948.0","128,045.0",...,"147,481.0","148,281.0","149,254.0","149,199.0","148,700.0","148,700.0","148,700.0","148,700.0","148,768.0",..
42,NaN,Brazil,"Hectares, Thousands",i,"234,900.0","233,480.2","232,060.4","230,640.6","229,220.8","227,805.0",...,"231,834.2","232,555.0","233,275.8","233,996.6","234,717.4","235,438.2","236,159.0","236,878.6","236,878.8",..
43,NaN,Bulgaria,"Hectares, Thousands",i,"6,159.0","6,159.0","6,159.0","6,159.0","6,159.0","6,164.0",...,"5,052.0","5,088.0","5,123.0","4,995.0","4,977.0","5,011.0","5,021.0","5,030.0","5,030.0","5,037.0"
44,NaN,China (People's Republic of),"Hectares, Thousands",i,"506,592.0","512,271.0","515,198.0","519,106.0","523,713.0","523,714.0",...,"528,916.8","528,885.1","528,799.5","528,801.5","528,695.0","528,633.4","528,552.9","528,531.1","528,528.7",..
45,NaN,Croatia,"Hectares, Thousands",i,..,..,..,..,..,..,...,"1,334.0","1,326.0","1,331.0","1,301.0","1,241.0","1,538.0","1,546.0","1,497.0","1,486.0","1,504.0"
46,NaN,Cyprus,"Hectares, Thousands",i,141.5,140.8,143.7,142.5,133.4,134.4,...,115.0,116.0,116.0,107.0,107.0,126.0,112.0,122.0,132.0,125.0
47,NaN,India,"Hectares, Thousands",i,"181,413.0","181,586.0","181,305.0","181,382.0","181,291.0","180,945.0",...,"179,573.0","179,670.0","179,642.0","179,698.0","179,721.0","179,674.0","179,674.0","179,674.0","179,674.0",..
48,NaN,Indonesia,"Hectares, Thousands",i,"45,083.0","41,524.0","41,351.0","42,016.0","41,971.0","42,978.0",...,"55,600.0","56,500.0","56,500.0","57,000.0","57,000.0","57,300.0","60,200.0","62,300.0","62,300.0",..
49,NaN,Kazakhstan,"Hectares, Thousands",i,..,..,"221,463.0","221,747.0","221,651.0","217,186.5",...,"217,161.8","216,988.5","217,012.1","216,994.1","216,799.4","216,259.7","216,242.1","216,213.8","216,036.5",..
50,NaN,Malta,"Hectares, Thousands",i,..,11.0,..,..,..,..,...,11.0,11.0,11.0,12.0,12.0,12.0,12.0,12.0,12.0,12.0
51,NaN,Philippines,"Hectares, Thousands",i,"11,140.0","11,157.0","11,115.0","11,065.0","11,015.0","11,015.0",...,"12,100.0","12,260.0","12,430.0","12,440.0","12,440.0","12,440.0","12,440.0","12,440.0","12,440.0",..
52,NaN,Romania,"Hectares, Thousands",i,"14,769.0","14,802.3","14,790.1","14,793.2","14,797.5","14,797.2",...,"14,156.0","13,982.0","13,733.0","13,905.0","13,830.0","13,858.0","13,521.0","13,378.0","13,414.0","13,826.0"
53,NaN,Russia,"Hectares, Thousands",i,..,..,"221,631.0","218,795.0","217,711.0","216,400.0",...,"215,494.0","215,494.0","215,494.0","215,494.0","215,494.0","215,494.0","215,494.0","215,494.0","215,494.0",..
54,NaN,South Africa,"Hectares, Thousands",i,"95,600.0","96,005.0","96,473.0","96,936.0","97,265.0","97,520.0",...,"96,891.0","96,374.0","96,341.0","96,341.0","96,341.0","96,341.0","96,341.0","96,341.0","96,341.0",..
55,NaN,Ukraine,"Hectares, Thousands",i,..,..,"41,929.0","41,890.0","41,861.0","41,853.0",...,"41,267.0","41,281.0","41,297.0","41,526.0","41,511.0","41,508.0","41,515.0","41,489.0","41,329.0",..
56,NaN,Viet Nam,"Hectares, Thousands",i,"6,726.0","6,751.0","7,025.0","7,087.0","7,140.0","7,079.0",...,"10,760.1","10,768.6","10,793.3","10,852.8","10,873.7","12,147.8","12,172.2","12,168.8","12,168.8",..
57,Data extracted on 19 Nov 2021 14:16 UTC (GMT) ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,NaN,NaN,NaN,NaN,1990,1991,1992,1993,1994,1995,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019

In [29]:
## Cleaning the dataset

df.drop([0,57,58,59], inplace = True)
df

,Time,Unnamed: 1,Unnamed: 2,Unnamed: 3,1990,1991,1992,1993,1994,1995,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
1,Australia,NaN,"Hectares, Thousands",i,"464,026.5","462,763.4","465,953.5","460,097.3","469,047.6","463,347.3",...,"397,451.0","391,686.2","405,473.6","396,615.3","406,269.0","384,557.9","371,078.3","393,797.2",..,..
2,Austria,NaN,"Hectares, Thousands",i,"3,458.0","3,477.0","3,467.8","3,448.3","3,449.3",..,...,"3,166.0","2,868.0","2,864.0","2,862.0","2,716.0","2,720.0","2,689.0","2,656.0","2,654.0","2,652.0"
3,Belgium,NaN,"Hectares, Thousands",i,"1,384.0","1,374.8","1,353.8","1,370.8","1,370.2","1,385.8",...,"1,358.0","1,337.0","1,334.0","1,339.0","1,333.0","1,331.0","1,353.0","1,329.0","1,356.0","1,359.0"
4,Canada,NaN,"Hectares, Thousands",i,"58,580.7","60,891.4","60,207.3","60,761.7","61,398.5","60,801.5",...,"64,627.4","65,066.5","68,418.4","68,036.6","67,516.7","67,552.3","68,141.0","69,855.0","68,117.0",..
5,Chile,NaN,"Hectares, Thousands",i,"15,899.0","15,789.0","15,556.0","15,477.0","15,450.0","15,330.0",...,"15,743.0","15,789.0","15,755.0","15,781.0","15,761.2","15,785.0","15,741.8","15,747.0",..,..
6,Colombia,NaN,"Hectares, Thousands",i,"45,083.0","44,884.0","44,983.0","44,903.0","44,865.0","44,513.0",...,"42,503.0","41,721.0","42,617.6","44,815.6","44,784.7","44,753.9","44,723.0","49,499.0","49,492.0",..
7,Costa Rica,NaN,"Hectares, Thousands",i,"2,198.6","2,203.6","2,160.0","2,113.0","2,095.0","2,048.0",...,"1,819.0","1,819.0","1,812.0","1,801.0","1,778.0","1,777.5","1,777.5","1,779.5","1,782.5",..
8,Czech Republic,NaN,"Hectares, Thousands",i,"4,288.0","4,285.0","4,283.0","4,282.0","4,281.0","4,280.0",...,"3,524.0","3,504.0","3,526.0","3,521.0","3,516.0","3,494.0","3,489.0","3,521.0","3,523.0","3,524.0"
9,Denmark,NaN,"Hectares, Thousands",i,"2,788.3","2,785.7","2,755.3","2,710.9","2,712.6","2,721.6",...,"2,676.0","2,673.0","2,664.0","2,628.0","2,652.0","2,633.0","2,625.0","2,631.0","2,633.0","2,626.0"
10,Estonia,NaN,"Hectares, Thousands",i,"1,357.8","1,374.5","1,374.1","1,320.6","1,100.7",990.8,...,949.0,946.0,956.0,966.0,975.0,994.0,"1,004.0",982.0,985.0,988.0
11,Finland,NaN,"Hectares, Thousands",i,"2,559.7","2,539.2","2,528.5","2,292.9","2,318.0","2,161.1",...,"2,292.0","2,287.0","2,285.0","2,259.0","2,267.0","2,273.0","2,275.0","2,272.0","2,272.0","2,274.0"
12,France,NaN,"Hectares, Thousands",i,"30,494.2","30,369.3","30,230.9","30,121.3","30,037.5","30,017.4",...,"29,311.0","28,853.0","29,001.0","28,976.0","28,930.0","29,115.0","29,089.0","29,101.0","29,020.0","29,024.0"
13,Germany,NaN,"Hectares, Thousands",i,"17,869.1","17,136.5","16,950.1","17,219.5","17,354.3","17,344.3",...,"16,704.0","16,721.0","16,667.0","16,700.0","16,725.0","16,731.0","16,659.0","16,687.0","16,645.0","16,666.0"
14,Greece,NaN,"Hectares, Thousands",i,"5,180.1","5,169.4","5,180.7","5,161.9","5,115.9","5,116.0",...,"5,426.0","5,532.0","5,135.0","5,213.0","5,407.0","5,292.0","5,260.0","5,152.0","5,288.0","5,153.0"
15,Hungary,NaN,"Hectares, Thousands",i,"6,473.1","6,459.7","6,135.7","6,129.1","6,122.0","6,179.3",...,"5,343.0","5,337.0","5,338.0","5,340.0","5,346.0","5,346.0","5,349.0","5,352.0","5,344.0","5,310.0"
16,Iceland,NaN,"Hectares, Thousands",i,"1,907.3","1,906.9","1,906.4","1,906.1","1,906.9","1,907.2",...,"1,591.0","1,591.0","1,591.0","1,591.0","1,591.0","1,591.0","1,591.0","1,591.0","1,591.0",..
17,Ireland,NaN,"Hectares, Thousands",i,"4,536.4","4,443.8","4,415.2","4,406.3","4,392.7","4,388.5",...,"4,569.0","4,556.0","4,532.0","4,478.0","4,465.0","4,431.0","4,461.0","4,489.0","4,516.0","4,524.0"
18,Israel,NaN,"Hectares, Thousands",i,435.0,435.0,435.0,435.0,435.0,430.0,...,283.2,289.2,298.3,292.3,309.8,306.0,308.2,297.1,293.5,..
19,Italy,NaN,"Hectares, Thousands",i,"18,166.3","17,570.6","17,203.0","16,484.1","16,426.0","16,172.3",...,"12,885.0","12,670.0","12,548.0","12,426.0","12,720.0","12,661.0","12,843.0","13,006.0","12,909.0","13,150.0"
20,Japan,NaN,"Hectares, Thousands",i,"5,242.7","5,204.7","5,164.5","5,124.8","5,082.0","5,038.3",...,"4,592.3","4,560.9","4,549.5","4,536.6","4,518.4","4,495.9","4,471.5","4,443.7","4,419.2",..
21,Korea,NaN,"Hectares, Thousands",i,"2,199.0","2,181.0","2,158.0","2,131.0","2,099.0","2,051.0",...,"1,754.0","1,737.0","1,768.0","1,749.0","1,727.1","1,714.0","1,678.1","1,654.8",..,..
22,Latvia,NaN,"Hectares, Thousands",i,"2,539.6","2,523.3","2,466.3","2,292.2","2,052.4","2,540.3",...,"1,806.0","1,816.0","1,841.0","1,878.0","1,873.0","1,885.0","1,931.0","1,932.0","1,938.0","1,959.0"
23,Lithuania,NaN,"Hectares, Thousands",i,"3,513.5","3,511.6","3,524.1","3,519.3","3,513.0","3,506.8",...,"2,772.0","2,806.0","2,842.0","2,891.0","2,952.0","3,006.0","2,954.0","2,935.0","2,947.0","2,975.0"
24,Luxembourg,NaN,"Hectares, Thousands",i,126.6,125.6,125.7,127.3,126.8,127.0,...,131.0,131.0,131.0,131.0,131.0,131.0,131.0,131.0,132.0,132.0
25,Mexico,NaN,"Hectares, Thousands",i,"105,151.0","106,154.0","106,177.0","106,180.0","106,190.0","106,195.0",...,"102,844.0","103,073.0","102,138.0","101,586.0","101,407.0","103,212.0","104,992.0","106,964.0",..,..
26,Netherlands,NaN,"Hectares, Thousands",i,"2,019.3","1,970.5","1,964.5","1,966.8","1,960.5","1,963.5",...,"1,872.0","1,858.0","1,842.0","1,848.0","1,839.0","1,846.0","1,796.0","1,790.0","1,822.0","1,816.0"
27,New Zealand,NaN,"Hectares, Thousands",i,"13,163.8","13,150.7","13,137.2","13,092.2","13,036.4","12,952.2",...,"11,408.0","11,371.0","11,209.0","11,106.0","11,122.0","10,850.0","10,674.0","10,779.0","10,632.0",..
28,Norway,NaN,"Hectares, Thousands",i,..,..,..,..,..,"1,025.5",...,"1,006.0",999.0,993.0,987.0,987.0,986.0,983.0,..,986.0,..
29,Poland,NaN,"Hectares, Thousands",i,"18,645.6","18,600.5","18,535.1","18,476.6","18,449.9","18,411.9",...,"14,603.0","14,780.0","14,529.0","14,410.0","14,424.0","14,398.0","14,406.0","14,498.0","14,540.0",..
30,Portugal,NaN,"Hectares, Thousands",i,"4,019.0","4,120.9","4,052.9","4,033.0","4,046.6","4,001.9",...,"3,654.0","3,650.0","3,665.0","3,718.0","3,700.0","3,695.0","3,636.0","3,603.0","3,591.0",..
31,Slovak Republic,NaN,"Hectares, Thousands",i,"2,416.6","2,416.6","2,418.8","2,420.7","2,446.0","2,445.9",...,"1,922.0","1,930.0","1,927.0","1,929.0","1,925.0","1,922.0","1,919.0","1,911.0","1,920.0","1,916.0"
32,Slovenia,NaN,"Hectares, Thousands",i,..,841.9,567.2,565.4,522.0,538.0,...,483.0,458.0,480.0,479.0,482.0,477.0,478.0,481.0,478.0,480.0
33,Spain,NaN,"Hectares, Thousands",i,"30,625.2","30,054.1","30,000.0","29,755.9","29,597.5","29,863.7",...,"23,719.0","23,894.0","23,463.0","23,495.0","23,572.0","23,897.0","23,816.0","23,841.0","24,202.0","24,372.0"
34,Sweden,NaN,"Hectares, Thousands",i,"3,416.4","3,358.0","3,336.0","3,200.8","3,371.0","3,148.2",...,"3,074.0","3,063.0","3,032.0","3,036.0","3,036.0","3,028.0","3,021.0","3,011.0","3,000.0","3,005.0"
35,Switzerland,NaN,"Hectares, Thousands",i,..,..,..,..,..,..,...,"1,537.0","1,534.0","1,531.0","1,529.0","1,526.0","1,523.0","1,521.0","1,518.0","1,515.0","1,512.0"
36,Turkey,NaN,"Hectares, Thousands",i,"42,003.0","40,031.0","39,952.0","39,912.0","40,048.0","39,211.0",...,"39,011.7","38,230.7","38,398.7","38,421.7","38,559.7","38,550.7","38,327.7","37,963.0","37,797.0",..
37,United Kingdom,NaN,"Hectares, Thousands",i,"16,998.5","16,928.3","16,851.7","16,355.5","16,177.0","16,126.0",...,"17,231.0","17,172.0","17,282.0","17,259.0","17,240.0","17,144.0","17,357.0","17,472.0","17,357.0","17,529.0"
38,United States,NaN,"Hectares, Thousands",i,"426,948.0","426,948.0","425,429.0","422,948.0","421,139.0","420,139.0",...,"408,426.2","406,927.7","423,893.2","422,481.0","424,330.2","422,568.3","422,826.2","422,826.2",..,..
39,European Union (28 countries),NaN,"Hectares, Thousands",i,..,..,..,..,..,..,...,"180,137.0","179,365.0","178,198.0","178,099.0","178,393.0","178,996.0","178,751.0","178,822.0","179,145.0",..
40,Non-OECD Economies,NaN,NaN,NaN,..,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
41,Non-OECD Economies,Argentina,"Hectares, Thousands",i,"127,565.0","127,660.0","127,755.0","127,850.0","127,948.0","128,045.0",...,"147,481.0","148,281.0","149,254.0","149,199.0","148,700.0","148,700.0","148,700.0","148,700.0","148,768.0",..
42,NaN,Brazil,"Hectares, Thousands",i,"234,900.0","233,480.2","232,060.4","230,640.6","229,220.8","227,805.0",...,"231,834.2","232,555.0","233,275.8","233,996.6","234,717.4","235,438.2","236,159.0","236,878.6","236,878.8",..
43,NaN,Bulgaria,"Hectares, Thousands",i,"6,159.0","6,159.0","6,159.0","6,159.0","6,159.0","6,164.0",...,"5,052.0","5,088.0","5,123.0","4,995.0","4,977.0","5,011.0","5,021.0","5,030.0","5,030.0","5,037.0"
44,NaN,China (People's Republic of),"Hectares, Thousands",i,"506,592.0","512,271.0","515,198.0","519,106.0","523,713.0","523,714.0",...,"528,916.8","528,885.1","528,799.5","528,801.5","528,695.0","528,633.4","528,552.9","528,531.1","528,528.7",..
45,NaN,Croatia,"Hectares, Thousands",i,..,..,..,..,..,..,...,"1,334.0","1,326.0","1,331.0","1,301.0","1,241.0","1,538.0","1,546.0","1,497.0","1,486.0","1,504.0"
46,NaN,Cyprus,"Hectares, Thousands",i,141.5,140.8,143.7,142.5,133.4,134.4,...,115.0,116.0,116.0,107.0,107.0,126.0,112.0,122.0,132.0,125.0
47,NaN,India,"Hectares, Thousands",i,"181,413.0","181,586.0","181,305.0","181,382.0","181,291.0","180,945.0",...,"179,573.0","179,670.0","179,642.0","179,698.0","179,721.0","179,674.0","179,674.0","179,674.0","179,674.0",..
48,NaN,Indonesia,"Hectares, Thousands",i,"45,083.0","41,524.0","41,351.0","42,016.0","41,971.0","42,978.0",...,"55,600.0","56,500.0","56,500.0","57,000.0","57,000.0","57,300.0","60,200.0","62,300.0","62,300.0",..
49,NaN,Kazakhstan,"Hectares, Thousands",i,..,..,"221,463.0","221,747.0","221,651.0","217,186.5",...,"217,161.8","216,988.5","217,012.1","216,994.1","216,799.4","216,259.7","216,242.1","216,213.8","216,036.5",..
50,NaN,Malta,"Hectares, Thousands",i,..,11.0,..,..,..,..,...,11.0,11.0,11.0,12.0,12.0,12.0,12.0,12.0,12.0,12.0
51,NaN,Philippines,"Hectares, Thousands",i,"11,140.0","11,157.0","11,115.0","11,065.0","11,015.0","11,015.0",...,"12,100.0","12,260.0","12,430.0","12,440.0","12,440.0","12,440.0","12,440.0","12,440.0","12,440.0",..
52,NaN,Romania,"Hectares, Thousands",i,"14,769.0","14,802.3","14,790.1","14,793.2","14,797.5","14,797.2",...,"14,156.0","13,982.0","13,733.0","13,905.0","13,830.0","13,858.0","13,521.0","13,378.0","13,414.0","13,826.0"
53,NaN,Russia,"Hectares, Thousands",i,..,..,"221,631.0","218,795.0","217,711.0","216,400.0",...,"215,494.0","215,494.0","215,494.0","215,494.0","215,494.0","215,494.0","215,494.0","215,494.0","215,494.0",..
54,NaN,South Africa,"Hectares, Thousands",i,"95,600.0","96,005.0","96,473.0","96,936.0","97,265.0","97,520.0",...,"96,891.0","96,374.0","96,341.0","96,341.0","96,341.0","96,341.0","96,341.0","96,341.0","96,341.0",..
55,NaN,Ukraine,"Hectares, Thousands",i,..,..,"41,929.0","41,890.0","41,861.0","41,853.0",...,"41,267.0","41,281.0","41,297.0","41,526.0","41,511.0","41,508.0","41,515.0","41,489.0","41,329.0",..
56,NaN,Viet Nam,"Hectares, Thousands",i,"6,726.0","6,751.0","7,025.0","7,087.0","7,140.0","7,079.0",...,"10,760.1","10,768.6","10,793.3","10,852.8","10,873.7","12,147.8","12,172.2","12,168.8","12,168.8",..

In [30]:
df.drop(labels = ["Unnamed: 3"], axis = 1, inplace = True)

df

,Time,Unnamed: 1,Unnamed: 2,1990,1991,1992,1993,1994,1995,1996,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
1,Australia,NaN,"Hectares, Thousands","464,026.5","462,763.4","465,953.5","460,097.3","469,047.6","463,347.3","465,219.6",...,"397,451.0","391,686.2","405,473.6","396,615.3","406,269.0","384,557.9","371,078.3","393,797.2",..,..
2,Austria,NaN,"Hectares, Thousands","3,458.0","3,477.0","3,467.8","3,448.3","3,449.3",..,..,...,"3,166.0","2,868.0","2,864.0","2,862.0","2,716.0","2,720.0","2,689.0","2,656.0","2,654.0","2,652.0"
3,Belgium,NaN,"Hectares, Thousands","1,384.0","1,374.8","1,353.8","1,370.8","1,370.2","1,385.8","1,390.5",...,"1,358.0","1,337.0","1,334.0","1,339.0","1,333.0","1,331.0","1,353.0","1,329.0","1,356.0","1,359.0"
4,Canada,NaN,"Hectares, Thousands","58,580.7","60,891.4","60,207.3","60,761.7","61,398.5","60,801.5","63,182.5",...,"64,627.4","65,066.5","68,418.4","68,036.6","67,516.7","67,552.3","68,141.0","69,855.0","68,117.0",..
5,Chile,NaN,"Hectares, Thousands","15,899.0","15,789.0","15,556.0","15,477.0","15,450.0","15,330.0","15,232.0",...,"15,743.0","15,789.0","15,755.0","15,781.0","15,761.2","15,785.0","15,741.8","15,747.0",..,..
6,Colombia,NaN,"Hectares, Thousands","45,083.0","44,884.0","44,983.0","44,903.0","44,865.0","44,513.0","44,920.0",...,"42,503.0","41,721.0","42,617.6","44,815.6","44,784.7","44,753.9","44,723.0","49,499.0","49,492.0",..
7,Costa Rica,NaN,"Hectares, Thousands","2,198.6","2,203.6","2,160.0","2,113.0","2,095.0","2,048.0","1,995.0",...,"1,819.0","1,819.0","1,812.0","1,801.0","1,778.0","1,777.5","1,777.5","1,779.5","1,782.5",..
8,Czech Republic,NaN,"Hectares, Thousands","4,288.0","4,285.0","4,283.0","4,282.0","4,281.0","4,280.0","4,279.0",...,"3,524.0","3,504.0","3,526.0","3,521.0","3,516.0","3,494.0","3,489.0","3,521.0","3,523.0","3,524.0"
9,Denmark,NaN,"Hectares, Thousands","2,788.3","2,785.7","2,755.3","2,710.9","2,712.6","2,721.6","3,007.4",...,"2,676.0","2,673.0","2,664.0","2,628.0","2,652.0","2,633.0","2,625.0","2,631.0","2,633.0","2,626.0"
10,Estonia,NaN,"Hectares, Thousands","1,357.8","1,374.5","1,374.1","1,320.6","1,100.7",990.8,"1,004.9",...,949.0,946.0,956.0,966.0,975.0,994.0,"1,004.0",982.0,985.0,988.0
11,Finland,NaN,"Hectares, Thousands","2,559.7","2,539.2","2,528.5","2,292.9","2,318.0","2,161.1","2,143.6",...,"2,292.0","2,287.0","2,285.0","2,259.0","2,267.0","2,273.0","2,275.0","2,272.0","2,272.0","2,274.0"
12,France,NaN,"Hectares, Thousands","30,494.2","30,369.3","30,230.9","30,121.3","30,037.5","30,017.4","29,890.1",...,"29,311.0","28,853.0","29,001.0","28,976.0","28,930.0","29,115.0","29,089.0","29,101.0","29,020.0","29,024.0"
13,Germany,NaN,"Hectares, Thousands","17,869.1","17,136.5","16,950.1","17,219.5","17,354.3","17,344.3","17,650.6",...,"16,704.0","16,721.0","16,667.0","16,700.0","16,725.0","16,731.0","16,659.0","16,687.0","16,645.0","16,666.0"
14,Greece,NaN,"Hectares, Thousands","5,180.1","5,169.4","5,180.7","5,161.9","5,115.9","5,116.0","5,109.2",...,"5,426.0","5,532.0","5,135.0","5,213.0","5,407.0","5,292.0","5,260.0","5,152.0","5,288.0","5,153.0"
15,Hungary,NaN,"Hectares, Thousands","6,473.1","6,459.7","6,135.7","6,129.1","6,122.0","6,179.3","6,184.4",...,"5,343.0","5,337.0","5,338.0","5,340.0","5,346.0","5,346.0","5,349.0","5,352.0","5,344.0","5,310.0"
16,Iceland,NaN,"Hectares, Thousands","1,907.3","1,906.9","1,906.4","1,906.1","1,906.9","1,907.2","1,903.3",...,"1,591.0","1,591.0","1,591.0","1,591.0","1,591.0","1,591.0","1,591.0","1,591.0","1,591.0",..
17,Ireland,NaN,"Hectares, Thousands","4,536.4","4,443.8","4,415.2","4,406.3","4,392.7","4,388.5","4,341.4",...,"4,569.0","4,556.0","4,532.0","4,478.0","4,465.0","4,431.0","4,461.0","4,489.0","4,516.0","4,524.0"
18,Israel,NaN,"Hectares, Thousands",435.0,435.0,435.0,435.0,435.0,430.0,421.8,...,283.2,289.2,298.3,292.3,309.8,306.0,308.2,297.1,293.5,..
19,Italy,NaN,"Hectares, Thousands","18,166.3","17,570.6","17,203.0","16,484.1","16,426.0","16,172.3","15,698.1",...,"12,885.0","12,670.0","12,548.0","12,426.0","12,720.0","12,661.0","12,843.0","13,006.0","12,909.0","13,150.0"
20,Japan,NaN,"Hectares, Thousands","5,242.7","5,204.7","5,164.5","5,124.8","5,082.0","5,038.3","4,993.5",...,"4,592.3","4,560.9","4,549.5","4,536.6","4,518.4","4,495.9","4,471.5","4,443.7","4,419.2",..
21,Korea,NaN,"Hectares, Thousands","2,199.0","2,181.0","2,158.0","2,131.0","2,099.0","2,051.0","2,008.0",...,"1,754.0","1,737.0","1,768.0","1,749.0","1,727.1","1,714.0","1,678.1","1,654.8",..,..
22,Latvia,NaN,"Hectares, Thousands","2,539.6","2,523.3","2,466.3","2,292.2","2,052.4","2,540.3","2,541.2",...,"1,806.0","1,816.0","1,841.0","1,878.0","1,873.0","1,885.0","1,931.0","1,932.0","1,938.0","1,959.0"
23,Lithuania,NaN,"Hectares, Thousands","3,513.5","3,511.6","3,524.1","3,519.3","3,513.0","3,506.8","3,504.0",...,"2,772.0","2,806.0","2,842.0","2,891.0","2,952.0","3,006.0","2,954.0","2,935.0","2,947.0","2,975.0"
24,Luxembourg,NaN,"Hectares, Thousands",126.6,125.6,125.7,127.3,126.8,127.0,126.4,...,131.0,131.0,131.0,131.0,131.0,131.0,131.0,131.0,132.0,132.0
25,Mexico,NaN,"Hectares, Thousands","105,151.0","106,154.0","106,177.0","106,180.0","106,190.0","106,195.0","106,310.0",...,"102,844.0","103,073.0","102,138.0","101,586.0","101,407.0","103,212.0","104,992.0","106,964.0",..,..
26,Netherlands,NaN,"Hectares, Thousands","2,019.3","1,970.5","1,964.5","1,966.8","1,960.5","1,963.5","1,960.4",...,"1,872.0","1,858.0","1,842.0","1,848.0","1,839.0","1,846.0","1,796.0","1,790.0","1,822.0","1,816.0"
27,New Zealand,NaN,"Hectares, Thousands","13,163.8","13,150.7","13,137.2","13,092.2","13,036.4","12,952.2","12,885.6",...,"11,408.0","11,371.0","11,209.0","11,106.0","11,122.0","10,850.0","10,674.0","10,779.0","10,632.0",..
28,Norway,NaN,"Hectares, Thousands",..,..,..,..,..,"1,025.5","1,031.2",...,"1,006.0",999.0,993.0,987.0,987.0,986.0,983.0,..,986.0,..
29,Poland,NaN,"Hectares, Thousands","18,645.6","18,600.5","18,535.1","18,476.6","18,449.9","18,411.9","18,275.2",...,"14,603.0","14,780.0","14,529.0","14,410.0","14,424.0","14,398.0","14,406.0","14,498.0","14,540.0",..
30,Portugal,NaN,"Hectares, Thousands","4,019.0","4,120.9","4,052.9","4,033.0","4,046.6","4,001.9","3,987.3",...,"3,654.0","3,650.0","3,665.0","3,718.0","3,700.0","3,695.0","3,636.0","3,603.0","3,591.0",..
31,Slovak Republic,NaN,"Hectares, Thousands","2,416.6","2,416.6","2,418.8","2,420.7","2,446.0","2,445.9","2,445.6",...,"1,922.0","1,930.0","1,927.0","1,929.0","1,925.0","1,922.0","1,919.0","1,911.0","1,920.0","1,916.0"
32,Slovenia,NaN,"Hectares, Thousands",..,841.9,567.2,565.4,522.0,538.0,524.5,...,483.0,458.0,480.0,479.0,482.0,477.0,478.0,481.0,478.0,480.0
33,Spain,NaN,"Hectares, Thousands","30,625.2","30,054.1","30,000.0","29,755.9","29,597.5","29,863.7","29,694.2",...,"23,719.0","23,894.0","23,463.0","23,495.0","23,572.0","23,897.0","23,816.0","23,841.0","24,202.0","24,372.0"
34,Sweden,NaN,"Hectares, Thousands","3,416.4","3,358.0","3,336.0","3,200.8","3,371.0","3,148.2","3,191.2",...,"3,074.0","3,063.0","3,032.0","3,036.0","3,036.0","3,028.0","3,021.0","3,011.0","3,000.0","3,005.0"
35,Switzerland,NaN,"Hectares, Thousands",..,..,..,..,..,..,..,...,"1,537.0","1,534.0","1,531.0","1,529.0","1,526.0","1,523.0","1,521.0","1,518.0","1,515.0","1,512.0"
36,Turkey,NaN,"Hectares, Thousands","42,003.0","40,031.0","39,952.0","39,912.0","40,048.0","39,211.0","39,363.0",...,"39,011.7","38,230.7","38,398.7","38,421.7","38,559.7","38,550.7","38,327.7","37,963.0","37,797.0",..
37,United Kingdom,NaN,"Hectares, Thousands","16,998.5","16,928.3","16,851.7","16,355.5","16,177.0","16,126.0","16,193.6",...,"17,231.0","17,172.0","17,282.0","17,259.0","17,240.0","17,144.0","17,357.0","17,472.0","17,357.0","17,529.0"
38,United States,NaN,"Hectares, Thousands","426,948.0","426,948.0","425,429.0","422,948.0","421,139.0","420,139.0","416,306.0",...,"408,426.2","406,927.7","423,893.2","422,481.0","424,330.2","422,568.3","422,826.2","422,826.2",..,..
39,European Union (28 countries),NaN,"Hectares, Thousands",..,..,..,..,..,..,..,...,"180,137.0","179,365.0","178,198.0","178,099.0","178,393.0","178,996.0","178,751.0","178,822.0","179,145.0",..
40,Non-OECD Economies,NaN,NaN,..,..,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
41,Non-OECD Economies,Argentina,"Hectares, Thousands","127,565.0","127,660.0","127,755.0","127,850.0","127,948.0","128,045.0","128,142.0",...,"147,481.0","148,281.0","149,254.0","149,199.0","148,700.0","148,700.0","148,700.0","148,700.0","148,768.0",..
42,NaN,Brazil,"Hectares, Thousands","234,900.0","233,480.2","232,060.4","230,640.6","229,220.8","227,805.0","227,908.7",...,"231,834.2","232,555.0","233,275.8","233,996.6","234,717.4","235,438.2","236,159.0","236,878.6","236,878.8",..
43,NaN,Bulgaria,"Hectares, Thousands","6,159.0","6,159.0","6,159.0","6,159.0","6,159.0","6,164.0","6,164.0",...,"5,052.0","5,088.0","5,123.0","4,995.0","4,977.0","5,011.0","5,021.0","5,030.0","5,030.0","5,037.0"
44,NaN,China (People's Republic of),"Hectares, Thousands","506,592.0","512,271.0","515,198.0","519,106.0","523,713.0","523,714.0","523,752.0",...,"528,916.8","528,885.1","528,799.5","528,801.5","528,695.0","528,633.4","528,552.9","528,531.1","528,528.7",..
45,NaN,Croatia,"Hectares, Thousands",..,..,..,..,..,..,..,...,"1,334.0","1,326.0","1,331.0","1,301.0","1,241.0","1,538.0","1,546.0","1,497.0","1,486.0","1,504.0"
46,NaN,Cyprus,"Hectares, Thousands",141.5,140.8,143.7,142.5,133.4,134.4,136.4,...,115.0,116.0,116.0,107.0,107.0,126.0,112.0,122.0,132.0,125.0
47,NaN,India,"Hectares, Thousands","181,413.0","181,586.0","181,305.0","181,382.0","181,291.0","180,945.0","180,589.0",...,"179,573.0","179,670.0","179,642.0","179,698.0","179,721.0","179,674.0","179,674.0","179,674.0","179,674.0",..
48,NaN,Indonesia,"Hectares, Thousands","45,083.0","41,524.0","41,351.0","42,016.0","41,971.0","42,978.0","42,968.0",...,"55,600.0","56,500.0","56,500.0","57,000.0","57,000.0","57,300.0","60,200.0","62,300.0","62,300.0",..
49,NaN,Kazakhstan,"Hectares, Thousands",..,..,"221,463.0","221,747.0","221,651.0","217,186.5","215,473.6",...,"217,161.8","216,988.5","217,012.1","216,994.1","216,799.4","216,259.7","216,242.1","216,213.8","216,036.5",..
50,NaN,Malta,"Hectares, Thousands",..,11.0,..,..,..,..,..,...,11.0,11.0,11.0,12.0,12.0,12.0,12.0,12.0,12.0,12.0
51,NaN,Philippines,"Hectares, Thousands","11,140.0","11,157.0","11,115.0","11,065.0","11,015.0","11,015.0","11,105.0",...,"12,100.0","12,260.0","12,430.0","12,440.0","12,440.0","12,440.0","12,440.0","12,440.0","12,440.0",..
52,NaN,Romania,"Hectares, Thousands","14,769.0","14,802.3","14,790.1","14,793.2","14,797.5","14,797.2","14,787.1",...,"14,156.0","13,982.0","13,733.0","13,905.0","13,830.0","13,858.0","13,521.0","13,378.0","13,414.0","13,826.0"
53,NaN,Russia,"Hectares, Thousands",..,..,"221,631.0","218,795.0","217,711.0","216,400.0","216,111.0",...,"215,494.0","215,494.0","215,494.0","215,494.0","215,494.0","215,494.0","215,494.0","215,494.0","215,494.0",..
54,NaN,South Africa,"Hectares, Thousands","95,600.0","96,005.0","96,473.0","96,936.0","97,265.0","97,520.0","97,890.0",...,"96,891.0","96,374.0","96,341.0","96,341.0","96,341.0","96,341.0","96,341.0","96,341.0","96,341.0",..
55,NaN,Ukraine,"Hectares, Thousands",..,..,"41,929.0","41,890.0","41,861.0","41,853.0","41,840.0",...,"41,267.0","41,281.0","41,297.0","41,526.0","41,511.0","41,508.0","41,515.0","41,489.0","41,329.0",..
56,NaN,Viet Nam,"Hectares, Thousands","6,726.0","6,751.0","7,025.0","7,087.0","7,140.0","7,079.0","7,682.0",...,"10,760.1","10,768.6","10,793.3","10,852.8","10,873.7","12,147.8","12,172.2","12,168.8","12,168.8",..

In [31]:
df.rename(columns={"Time": "OECD Economies", "Unnamed: 1": "Non-OECD Economies", "Unnamed: 2": "Unit"}, inplace = True)

In [32]:
df

,OECD Economies,Non-OECD Economies,Unit,1990,1991,1992,1993,1994,1995,1996,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
1,Australia,NaN,"Hectares, Thousands","464,026.5","462,763.4","465,953.5","460,097.3","469,047.6","463,347.3","465,219.6",...,"397,451.0","391,686.2","405,473.6","396,615.3","406,269.0","384,557.9","371,078.3","393,797.2",..,..
2,Austria,NaN,"Hectares, Thousands","3,458.0","3,477.0","3,467.8","3,448.3","3,449.3",..,..,...,"3,166.0","2,868.0","2,864.0","2,862.0","2,716.0","2,720.0","2,689.0","2,656.0","2,654.0","2,652.0"
3,Belgium,NaN,"Hectares, Thousands","1,384.0","1,374.8","1,353.8","1,370.8","1,370.2","1,385.8","1,390.5",...,"1,358.0","1,337.0","1,334.0","1,339.0","1,333.0","1,331.0","1,353.0","1,329.0","1,356.0","1,359.0"
4,Canada,NaN,"Hectares, Thousands","58,580.7","60,891.4","60,207.3","60,761.7","61,398.5","60,801.5","63,182.5",...,"64,627.4","65,066.5","68,418.4","68,036.6","67,516.7","67,552.3","68,141.0","69,855.0","68,117.0",..
5,Chile,NaN,"Hectares, Thousands","15,899.0","15,789.0","15,556.0","15,477.0","15,450.0","15,330.0","15,232.0",...,"15,743.0","15,789.0","15,755.0","15,781.0","15,761.2","15,785.0","15,741.8","15,747.0",..,..
6,Colombia,NaN,"Hectares, Thousands","45,083.0","44,884.0","44,983.0","44,903.0","44,865.0","44,513.0","44,920.0",...,"42,503.0","41,721.0","42,617.6","44,815.6","44,784.7","44,753.9","44,723.0","49,499.0","49,492.0",..
7,Costa Rica,NaN,"Hectares, Thousands","2,198.6","2,203.6","2,160.0","2,113.0","2,095.0","2,048.0","1,995.0",...,"1,819.0","1,819.0","1,812.0","1,801.0","1,778.0","1,777.5","1,777.5","1,779.5","1,782.5",..
8,Czech Republic,NaN,"Hectares, Thousands","4,288.0","4,285.0","4,283.0","4,282.0","4,281.0","4,280.0","4,279.0",...,"3,524.0","3,504.0","3,526.0","3,521.0","3,516.0","3,494.0","3,489.0","3,521.0","3,523.0","3,524.0"
9,Denmark,NaN,"Hectares, Thousands","2,788.3","2,785.7","2,755.3","2,710.9","2,712.6","2,721.6","3,007.4",...,"2,676.0","2,673.0","2,664.0","2,628.0","2,652.0","2,633.0","2,625.0","2,631.0","2,633.0","2,626.0"
10,Estonia,NaN,"Hectares, Thousands","1,357.8","1,374.5","1,374.1","1,320.6","1,100.7",990.8,"1,004.9",...,949.0,946.0,956.0,966.0,975.0,994.0,"1,004.0",982.0,985.0,988.0
11,Finland,NaN,"Hectares, Thousands","2,559.7","2,539.2","2,528.5","2,292.9","2,318.0","2,161.1","2,143.6",...,"2,292.0","2,287.0","2,285.0","2,259.0","2,267.0","2,273.0","2,275.0","2,272.0","2,272.0","2,274.0"
12,France,NaN,"Hectares, Thousands","30,494.2","30,369.3","30,230.9","30,121.3","30,037.5","30,017.4","29,890.1",...,"29,311.0","28,853.0","29,001.0","28,976.0","28,930.0","29,115.0","29,089.0","29,101.0","29,020.0","29,024.0"
13,Germany,NaN,"Hectares, Thousands","17,869.1","17,136.5","16,950.1","17,219.5","17,354.3","17,344.3","17,650.6",...,"16,704.0","16,721.0","16,667.0","16,700.0","16,725.0","16,731.0","16,659.0","16,687.0","16,645.0","16,666.0"
14,Greece,NaN,"Hectares, Thousands","5,180.1","5,169.4","5,180.7","5,161.9","5,115.9","5,116.0","5,109.2",...,"5,426.0","5,532.0","5,135.0","5,213.0","5,407.0","5,292.0","5,260.0","5,152.0","5,288.0","5,153.0"
15,Hungary,NaN,"Hectares, Thousands","6,473.1","6,459.7","6,135.7","6,129.1","6,122.0","6,179.3","6,184.4",...,"5,343.0","5,337.0","5,338.0","5,340.0","5,346.0","5,346.0","5,349.0","5,352.0","5,344.0","5,310.0"
16,Iceland,NaN,"Hectares, Thousands","1,907.3","1,906.9","1,906.4","1,906.1","1,906.9","1,907.2","1,903.3",...,"1,591.0","1,591.0","1,591.0","1,591.0","1,591.0","1,591.0","1,591.0","1,591.0","1,591.0",..
17,Ireland,NaN,"Hectares, Thousands","4,536.4","4,443.8","4,415.2","4,406.3","4,392.7","4,388.5","4,341.4",...,"4,569.0","4,556.0","4,532.0","4,478.0","4,465.0","4,431.0","4,461.0","4,489.0","4,516.0","4,524.0"
18,Israel,NaN,"Hectares, Thousands",435.0,435.0,435.0,435.0,435.0,430.0,421.8,...,283.2,289.2,298.3,292.3,309.8,306.0,308.2,297.1,293.5,..
19,Italy,NaN,"Hectares, Thousands","18,166.3","17,570.6","17,203.0","16,484.1","16,426.0","16,172.3","15,698.1",...,"12,885.0","12,670.0","12,548.0","12,426.0","12,720.0","12,661.0","12,843.0","13,006.0","12,909.0","13,150.0"
20,Japan,NaN,"Hectares, Thousands","5,242.7","5,204.7","5,164.5","5,124.8","5,082.0","5,038.3","4,993.5",...,"4,592.3","4,560.9","4,549.5","4,536.6","4,518.4","4,495.9","4,471.5","4,443.7","4,419.2",..
21,Korea,NaN,"Hectares, Thousands","2,199.0","2,181.0","2,158.0","2,131.0","2,099.0","2,051.0","2,008.0",...,"1,754.0","1,737.0","1,768.0","1,749.0","1,727.1","1,714.0","1,678.1","1,654.8",..,..
22,Latvia,NaN,"Hectares, Thousands","2,539.6","2,523.3","2,466.3","2,292.2","2,052.4","2,540.3","2,541.2",...,"1,806.0","1,816.0","1,841.0","1,878.0","1,873.0","1,885.0","1,931.0","1,932.0","1,938.0","1,959.0"
23,Lithuania,NaN,"Hectares, Thousands","3,513.5","3,511.6","3,524.1","3,519.3","3,513.0","3,506.8","3,504.0",...,"2,772.0","2,806.0","2,842.0","2,891.0","2,952.0","3,006.0","2,954.0","2,935.0","2,947.0","2,975.0"
24,Luxembourg,NaN,"Hectares, Thousands",126.6,125.6,125.7,127.3,126.8,127.0,126.4,...,131.0,131.0,131.0,131.0,131.0,131.0,131.0,131.0,132.0,132.0
25,Mexico,NaN,"Hectares, Thousands","105,151.0","106,154.0","106,177.0","106,180.0","106,190.0","106,195.0","106,310.0",...,"102,844.0","103,073.0","102,138.0","101,586.0","101,407.0","103,212.0","104,992.0","106,964.0",..,..
26,Netherlands,NaN,"Hectares, Thousands","2,019.3","1,970.5","1,964.5","1,966.8","1,960.5","1,963.5","1,960.4",...,"1,872.0","1,858.0","1,842.0","1,848.0","1,839.0","1,846.0","1,796.0","1,790.0","1,822.0","1,816.0"
27,New Zealand,NaN,"Hectares, Thousands","13,163.8","13,150.7","13,137.2","13,092.2","13,036.4","12,952.2","12,885.6",...,"11,408.0","11,371.0","11,209.0","11,106.0","11,122.0","10,850.0","10,674.0","10,779.0","10,632.0",..
28,Norway,NaN,"Hectares, Thousands",..,..,..,..,..,"1,025.5","1,031.2",...,"1,006.0",999.0,993.0,987.0,987.0,986.0,983.0,..,986.0,..
29,Poland,NaN,"Hectares, Thousands","18,645.6","18,600.5","18,535.1","18,476.6","18,449.9","18,411.9","18,275.2",...,"14,603.0","14,780.0","14,529.0","14,410.0","14,424.0","14,398.0","14,406.0","14,498.0","14,540.0",..
30,Portugal,NaN,"Hectares, Thousands","4,019.0","4,120.9","4,052.9","4,033.0","4,046.6","4,001.9","3,987.3",...,"3,654.0","3,650.0","3,665.0","3,718.0","3,700.0","3,695.0","3,636.0","3,603.0","3,591.0",..
31,Slovak Republic,NaN,"Hectares, Thousands","2,416.6","2,416.6","2,418.8","2,420.7","2,446.0","2,445.9","2,445.6",...,"1,922.0","1,930.0","1,927.0","1,929.0","1,925.0","1,922.0","1,919.0","1,911.0","1,920.0","1,916.0"
32,Slovenia,NaN,"Hectares, Thousands",..,841.9,567.2,565.4,522.0,538.0,524.5,...,483.0,458.0,480.0,479.0,482.0,477.0,478.0,481.0,478.0,480.0
33,Spain,NaN,"Hectares, Thousands","30,625.2","30,054.1","30,000.0","29,755.9","29,597.5","29,863.7","29,694.2",...,"23,719.0","23,894.0","23,463.0","23,495.0","23,572.0","23,897.0","23,816.0","23,841.0","24,202.0","24,372.0"
34,Sweden,NaN,"Hectares, Thousands","3,416.4","3,358.0","3,336.0","3,200.8","3,371.0","3,148.2","3,191.2",...,"3,074.0","3,063.0","3,032.0","3,036.0","3,036.0","3,028.0","3,021.0","3,011.0","3,000.0","3,005.0"
35,Switzerland,NaN,"Hectares, Thousands",..,..,..,..,..,..,..,...,"1,537.0","1,534.0","1,531.0","1,529.0","1,526.0","1,523.0","1,521.0","1,518.0","1,515.0","1,512.0"
36,Turkey,NaN,"Hectares, Thousands","42,003.0","40,031.0","39,952.0","39,912.0","40,048.0","39,211.0","39,363.0",...,"39,011.7","38,230.7","38,398.7","38,421.7","38,559.7","38,550.7","38,327.7","37,963.0","37,797.0",..
37,United Kingdom,NaN,"Hectares, Thousands","16,998.5","16,928.3","16,851.7","16,355.5","16,177.0","16,126.0","16,193.6",...,"17,231.0","17,172.0","17,282.0","17,259.0","17,240.0","17,144.0","17,357.0","17,472.0","17,357.0","17,529.0"
38,United States,NaN,"Hectares, Thousands","426,948.0","426,948.0","425,429.0","422,948.0","421,139.0","420,139.0","416,306.0",...,"408,426.2","406,927.7","423,893.2","422,481.0","424,330.2","422,568.3","422,826.2","422,826.2",..,..
39,European Union (28 countries),NaN,"Hectares, Thousands",..,..,..,..,..,..,..,...,"180,137.0","179,365.0","178,198.0","178,099.0","178,393.0","178,996.0","178,751.0","178,822.0","179,145.0",..
40,Non-OECD Economies,NaN,NaN,..,..,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
41,Non-OECD Economies,Argentina,"Hectares, Thousands","127,565.0","127,660.0","127,755.0","127,850.0","127,948.0","128,045.0","128,142.0",...,"147,481.0","148,281.0","149,254.0","149,199.0","148,700.0","148,700.0","148,700.0","148,700.0","148,768.0",..
42,NaN,Brazil,"Hectares, Thousands","234,900.0","233,480.2","232,060.4","230,640.6","229,220.8","227,805.0","227,908.7",...,"231,834.2","232,555.0","233,275.8","233,996.6","234,717.4","235,438.2","236,159.0","236,878.6","236,878.8",..
43,NaN,Bulgaria,"Hectares, Thousands","6,159.0","6,159.0","6,159.0","6,159.0","6,159.0","6,164.0","6,164.0",...,"5,052.0","5,088.0","5,123.0","4,995.0","4,977.0","5,011.0","5,021.0","5,030.0","5,030.0","5,037.0"
44,NaN,China (People's Republic of),"Hectares, Thousands","506,592.0","512,271.0","515,198.0","519,106.0","523,713.0","523,714.0","523,752.0",...,"528,916.8","528,885.1","528,799.5","528,801.5","528,695.0","528,633.4","528,552.9","528,531.1","528,528.7",..
45,NaN,Croatia,"Hectares, Thousands",..,..,..,..,..,..,..,...,"1,334.0","1,326.0","1,331.0","1,301.0","1,241.0","1,538.0","1,546.0","1,497.0","1,486.0","1,504.0"
46,NaN,Cyprus,"Hectares, Thousands",141.5,140.8,143.7,142.5,133.4,134.4,136.4,...,115.0,116.0,116.0,107.0,107.0,126.0,112.0,122.0,132.0,125.0
47,NaN,India,"Hectares, Thousands","181,413.0","181,586.0","181,305.0","181,382.0","181,291.0","180,945.0","180,589.0",...,"179,573.0","179,670.0","179,642.0","179,698.0","179,721.0","179,674.0","179,674.0","179,674.0","179,674.0",..
48,NaN,Indonesia,"Hectares, Thousands","45,083.0","41,524.0","41,351.0","42,016.0","41,971.0","42,978.0","42,968.0",...,"55,600.0","56,500.0","56,500.0","57,000.0","57,000.0","57,300.0","60,200.0","62,300.0","62,300.0",..
49,NaN,Kazakhstan,"Hectares, Thousands",..,..,"221,463.0","221,747.0","221,651.0","217,186.5","215,473.6",...,"217,161.8","216,988.5","217,012.1","216,994.1","216,799.4","216,259.7","216,242.1","216,213.8","216,036.5",..
50,NaN,Malta,"Hectares, Thousands",..,11.0,..,..,..,..,..,...,11.0,11.0,11.0,12.0,12.0,12.0,12.0,12.0,12.0,12.0
51,NaN,Philippines,"Hectares, Thousands","11,140.0","11,157.0","11,115.0","11,065.0","11,015.0","11,015.0","11,105.0",...,"12,100.0","12,260.0","12,430.0","12,440.0","12,440.0","12,440.0","12,440.0","12,440.0","12,440.0",..
52,NaN,Romania,"Hectares, Thousands","14,769.0","14,802.3","14,790.1","14,793.2","14,797.5","14,797.2","14,787.1",...,"14,156.0","13,982.0","13,733.0","13,905.0","13,830.0","13,858.0","13,521.0","13,378.0","13,414.0","13,826.0"
53,NaN,Russia,"Hectares, Thousands",..,..,"221,631.0","218,795.0","217,711.0","216,400.0","216,111.0",...,"215,494.0","215,494.0","215,494.0","215,494.0","215,494.0","215,494.0","215,494.0","215,494.0","215,494.0",..
54,NaN,South Africa,"Hectares, Thousands","95,600.0","96,005.0","96,473.0","96,936.0","97,265.0","97,520.0","97,890.0",...,"96,891.0","96,374.0","96,341.0","96,341.0","96,341.0","96,341.0","96,341.0","96,341.0","96,341.0",..
55,NaN,Ukraine,"Hectares, Thousands",..,..,"41,929.0","41,890.0","41,861.0","41,853.0","41,840.0",...,"41,267.0","41,281.0","41,297.0","41,526.0","41,511.0","41,508.0","41,515.0","41,489.0","41,329.0",..
56,NaN,Viet Nam,"Hectares, Thousands","6,726.0","6,751.0","7,025.0","7,087.0","7,140.0","7,079.0","7,682.0",...,"10,760.1","10,768.6","10,793.3","10,852.8","10,873.7","12,147.8","12,172.2","12,168.8","12,168.8",..

In [33]:
df['OECD Economies'].replace('Non-OECD Economies', 'NaN', inplace = True)

In [34]:
## df.drop([40], inplace = True)

## correcting the index error after dropping 40

df.reset_index(drop=True, inplace=True)

In [35]:
## cleaning the commas
df.replace(',', '', regex=True, inplace = True)

In [36]:
df['1990'].dtypes

dtype('O')

In [37]:
type(df['1990'][1])

str

In [38]:
## Sum up the global landuse for agricultural purpose in each year
import numpy as np
cols = df.columns[3:]
df[cols] = df[cols].apply(pd.to_numeric, errors='coerce')
df[cols] = df[cols].replace(np.nan, 0, regex=True)
df[cols].sum()

1990    2595801.4
1991    2595526.8
1992    3081337.5
1993    3072351.6
1994    3081612.0
1995    3064055.4
1996    3063463.1
1997    3065381.0
1998    3060305.7
1999    3034740.9
2000    3245207.8
2001    3241554.4
2002    3231554.8
2003    3227680.8
2004    3235939.9
2005    3049688.9
2006    3229869.9
2007    3223675.8
2008    3215728.1
2009    3013081.9
2010    3191950.7
2011    3184182.4
2012    3217681.0
2013    3209873.1
2014    3221266.3
2015    3202150.6
2016    3193828.5
2017    3226588.8
2018    2284875.0
2019     163450.0
dtype: float64